# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 006758cabcec50191c0e495c3df9467f2f869af664e89808d8a0a98213cb06b7753d889eeb3b54b781d988fd0e483eb8670ba9ffeb9f277213729c736aace80f

test:
  secret_key_base: 6e943d4ebc79585f452a3705a4340473a5af1ba3e0cd49f951f0af6c2e27844dbbfea6bce55d3ab7be436d37c7b7eb25ab6802923361b8957a0f9579c63fedde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
